/**
 * CS1010 Semester 1 AY24/25
 * Exercise 1: Candy
 *
 * @file: candy-main.c
 * @author: XXX (Group YYY)
 */
#include "cs1010.h"
#include <math.h>

// DO NOT EDIT THIS FILE

long compute_num_of_boxes(long num_of_candies, long max_candies_per_box);

int main()
{
  long num_of_candies = cs1010_read_long();
  long max_candies_per_box = cs1010_read_long();

  long num_of_boxes = compute_num_of_boxes(num_of_candies, max_candies_per_box);

  cs1010_println_long(num_of_boxes);
}
