/**
 * CS1010 Semester 1 AY24/25
 * Exercise 3: Largest
 *
 * @file: largest-main.c
 * @author: XXX (Group YYY)
 */

#include "cs1010.h"
// DO NOT EDIT THIS FILE

long find_largest(long n);

int main()
{
  long n = cs1010_read_long();
  cs1010_println_long(find_largest(n));
}
