/**
 * CS1010 Semester 1 AY24/25
 * Exercise 3: Max
 *
 * @file: max-main.c
 * @author: XXX (Group YYY)
 */
#include "cs1010.h"

// DO NOT EDIT THIS FILE

long find_max(const long list[], long start, long end);

int main()
{
  long list[100000];
  long num_of_elems = cs1010_read_long();
  for (long i = 0; i < num_of_elems; i += 1) {
    list[i] = cs1010_read_long();
  }

  cs1010_println_long(find_max(list, 0, num_of_elems));
}
