/**
 * CS1010 Semester 1 AY24/25
 * Exercise 0: Ones
 *
 * @file: ones-main.c
 */

#include "cs1010.h"

// DO NOT EDIT THIS FILE

void print_last_digit(long input);
void print_all_but_last_digit(long input);

int main()
{
  long input = cs1010_read_long();
  print_last_digit(input);
  print_all_but_last_digit(input);
}
