/**
 * CS1010 Semester 1 AY24/25
 * Exercise 2: Parity
 *
 * @file: parity-main.c
 * @author: XXX (Group YYY)
 */
#include "cs1010.h"

// DO NOT EDIT THIS FILE

void print_parity(long input);

int main()
{
  long input = cs1010_read_long();

  print_parity(input);
}
