/**
 * CS1010 Semester 1 AY24/25
 * Exercise 4: Concat
 *
 * @file: concat-main.c
 */
#include "cs1010.h"

// DO NOT EDIT THIS FILE

char *concatenate(const char *str1, const char *str2);

int main()
{
  char *str1 = cs1010_read_word();
  char *str2 = cs1010_read_word();
  char *dest = concatenate(str1, str2);

  cs1010_println_string(dest);

  free(dest);
  free(str1);
  free(str2);
}
