/**
 * CS1010 Semester 1 AY24/25
 * Exercise 4: Length
 *
 * @file: length-main.c
 */
#include "cs1010.h"

// DO NOT EDIT THIS FILE

size_t length_of(const char *str);

int main()
{
  char *str = cs1010_read_line();
  cs1010_println_size_t(length_of(str));
  free(str);
}
